#version: '3.8'

services:
  db:
    image: postgres:17-alpine
    restart: always
    container_name: db-prisma
    ports:
      - '5433:5432'
    env_file:
      - apps/api/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    #    restart: always
    container_name: server-api
    env_file:
      - apps/api/.env
    ports:
      - "5000:5000"
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - prisma-engines:/usr/src/app/node_modules/@prisma/engines
      - ./apps/api/prisma:/usr/src/app/prisma

volumes:
  postgres-data:
  prisma-engines: