#version: '3.8'

services:
  db:
    image: postgres:17-alpine
    restart: always
    container_name: db-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tahsin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    #    restart: always
    container_name: server-api
    environment:
      PORT: 5000
      NODE_ENV: development
      DATABASE_URL: "postgresql://postgres:root@db:5432/tahsin?schema=public"
      JWT_SECRET: EVJcJtqzG2yLjgScB8bAM8iXLv54epqFurg9PFusS+M=
      JWT_EXPIRES_IN: 1d
      REFRESH_JWT_SECRET: qjh8o9dKxBb71VI83wJXmkfLpaIgcvfRNfjgEIEanZU=
      REFRESH_JWT_EXPIRES_IN: 7d
    ports:
      - "5000:5000"
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - prisma-engines:/usr/src/app/node_modules/@prisma/engines
      - ./apps/api/prisma:/usr/src/app/prisma

volumes:
  postgres-data:
  prisma-engines: